language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
env:
  - TOXENV=py35
  - TOXENV=docs

addons:
  apt:
    packages:
    - pandoc
install: pip install tox
script: tox
after_failure: cat .tox/log/tox-*.log
